export function validateSspm(buffer) {
  const view=new DataView(buffer);let p=0;
  const take=n=>{if(!Number.isSafeInteger(n)||n<0||p+n>view.byteLength)throw new Error('SSPM data is truncated or invalid.');const start=p;p+=n;return start;};
  const u8=()=>view.getUint8(take(1));const u16=()=>view.getUint16(take(2),true);const u32=()=>view.getUint32(take(4),true);const u64=()=>Number(view.getBigUint64(take(8),true));
  const jump=n=>{p=0;take(n);};const text=()=>take(u16());
  const position=()=>{const mode=u8();if(mode===0)take(2);else if(mode===1){const a=view.getFloat32(take(4),true),b=view.getFloat32(take(4),true);if(!Number.isFinite(a)||!Number.isFinite(b))throw new Error('Invalid note coordinates.');}else throw new Error('Invalid note position type.');};
  const field=(type,depth=0)=>{if(depth>8)throw new Error('SSPM metadata is nested too deeply.');if(type===1)take(1);else if(type===2)take(2);else if(type===3||type===5)take(4);else if(type===4||type===6)take(8);else if(type===7)position();else if(type===8||type===9)take(u16());else if(type===10||type===11)take(u32());else if(type===12){const subtype=u8(),count=u16();for(let i=0;i<count;i++)field(subtype,depth+1);}else throw new Error('Unsupported SSPM metadata.');};
  if(u32()!==0x6d2b5353)throw new Error('This is not an SSPM map.');const version=u16();
  if(version===1){take(2);for(let i=0;i<3;i++){let length=0;while(u8()!==10){if(++length>65536)throw new Error('Invalid SSPM text.');}}take(4);const count=u32();if(count<1||count>1000000)throw new Error('Unsupported note count.');u8();const cover=u8();if(cover===1){const height=u16(),width=u16();take(2);if(height>4096||width>4096)throw new Error('Map artwork is too large.');take(u64());}else if(cover===2)take(u64());else if(cover!==0)throw new Error('Invalid artwork type.');if(u8()!==1)throw new Error('The map needs embedded audio.');const audio=u64();if(audio<12)throw new Error('Map audio is missing.');take(audio);for(let i=0;i<count;i++){take(4);position();}return version;}
  if(version!==2)throw new Error('Only SSPM v1 and v2 are supported.');jump(0x26);const count=u32();if(count<1||count>1000000)throw new Error('Unsupported marker count.');take(3);if(u8()!==1)throw new Error('The map needs embedded audio.');const cover=u8();jump(0x30);const custom=u64();u64();const audioOffset=u64(),audioLength=u64(),coverOffset=u64(),coverLength=u64(),definitions=u64();u64();const markers=u64();u64();text();text();text();const authors=u16();for(let i=0;i<authors;i++)text();jump(custom);const fields=u16();for(let i=0;i<fields;i++){text();field(u8());}jump(audioOffset);if(audioLength<12)throw new Error('Map audio is missing.');take(audioLength);if(cover){jump(coverOffset);take(coverLength);}jump(definitions);const types=[],size=u8();let noteType=-1;const decoder=new TextDecoder();for(let i=0;i<size;i++){const length=u16(),start=take(length),name=decoder.decode(new Uint8Array(buffer,start,length));const attributes=[],number=u8();for(let j=0;j<number;j++)attributes.push(u8());if(u8()!==0)throw new Error('Invalid marker definition.');if(name==='ssp_note'&&attributes[0]===7)noteType=i;types.push(attributes);}if(noteType<0)throw new Error('Map has no supported notes.');jump(markers);let notes=0;for(let i=0;i<count;i++){take(4);const type=u8();if(!types[type])throw new Error('Unknown marker type.');if(type===noteType)notes++;for(const attribute of types[type])field(attribute);}if(!notes)throw new Error('Map has no notes.');return version;
}
